jobs:

  - job: Windows
    variables:
      OS: Windows
      LLVM: 9
    timeoutInMinutes: 299
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-latest'
    steps:
    - powershell: |
      dotnet test -c Debug -f netcoreapp2.2 | cat
      displayName: 'Install build tools'

trigger:
- master

coverage:
  status:           #Code coverage status will be posted to pull requests based on targets defined below.
    comments: on    #Off by default. When on, details about coverage for each file changed will be posted as a pull request comment. 
    diff:           #diff coverage is code coverage only for the lines changed in a pull request.
      target: 50%   #set this to a desired %. Default is 70%