language: shell

git:
  depth: false

# mono:
#  - latest

matrix:
  include:
#  - name: OS X 10.13
#    os: osx
#    osx_image: xcode9.3
  - name: OS X 10.14
    os: osx
    osx_image: xcode10.2
  - name: OS X 10.10
    os: osx
    osx_image: xcode6.4
#  - name: OS X 10.12
#    os: osx
#    osx_image: xcode8.3

# https://docs.travis-ci.com/user/caching/
before_script:
- |
    OS_X_VER=$(sw_vers | grep BuildVer | awk '{print $2}' | cut -c1-2); OS_X_VER=$((OS_X_VER-4))

    

- |
  DOTNET_Url=https://dot.net/v1/dotnet-install.sh; 
  if [ $OS_X_VER -ge 13 ]; then
      time (curl -ksSL $DOTNET_Url | bash /dev/stdin -c 3.0 -i ~/net)
      export PATH="$HOME/net:$PATH"
      export DOTNET_ROOT="$HOME/net"
      dotnet --info || true
      dotnet tool install -g BenchmarkDotNet.Tool
  fi

- | 
  MONO_Url=https://download.mono-project.com/archive/6.4.0/macos-10-universal/MonoFramework-MDK-6.4.0.198.macos10.xamarin.universal.pkg
  curl -o ~/mono.pkg $MONO_Url
  sudo installer -verbose -pkg ~/mono.pkg -target /
  export PATH="/Library/Frameworks/Mono.framework/Versions/Current/Commands:$PATH"

- 'mono --version; msbuild /version; echo ""; nuget 2>&1 | head -4'
  
script:
- export DOTNET_SYSTEM_NET_HTTP_USESOCKETSHTTPHANDLER=0
- export DOTNET_SKIP_FIRST_TIME_EXPERIENCE=1; export DOTNET_CLI_TELEMETRY_OPTOUT=1;
- export CI=false
#- dotnet restore --disable-parallel || true
- [ $OS_X_VER -ge 13 ] && (dotnet test -f netcoreapp3.0 | cat)
- [ $OS_X_VER -ge 13 ] && (bash benchmark.linux.sh || true)
- nuget restore || true

- 'pushd Tests4Mac; bash -e test-using-mono-only.sh; popd'
    

