version: 'Universe.CpuUsage Integration tests on Windows #{build}'
image:
- Ubuntu1804
# - Ubuntu1604
- Visual Studio 2019

skip_commits:
  files:
    - .circleci/*

platform: Any CPU
init:
- ps: |

    # copy paste it
    function Say { param( [string] $message )
        Write-Host "$(Get-Elapsed) " -NoNewline -ForegroundColor Magenta
        Write-Host "$message" -ForegroundColor Yellow
    }
    
    function Get-Elapsed
    {
        if ($Global:startAt -eq $null) { $Global:startAt = [System.Diagnostics.Stopwatch]::StartNew(); }
        [System.String]::Concat("[", (new-object System.DateTime(0)).AddMilliseconds($Global:startAt.ElapsedMilliseconds).ToString("mm:ss"), "]");
    }; Get-Elapsed | out-null;

- sh: |
    function header() {
      if [[ $(uname -s) != Darwin ]]; then
        startAt=${startAt:-$(date +%s)}; elapsed=$(date +%s); elapsed=$((elapsed-startAt)); elapsed=$(TZ=UTC date -d "@${elapsed}" "+%_H:%M:%S");
      fi
      LightGreen='\033[1;32m'; Yellow='\033[1;33m'; RED='\033[0;31m'; NC='\033[0m'; LightGray='\033[1;2m';
      printf "${LightGray}${elapsed:-}${NC} ${LightGreen}$1${NC} ${Yellow}$2${NC}\n"; 
    }
    counter=0; function Say() { echo ""; counter=$((counter+1)); header "STEP $counter" "$1"; }; Say "" >/dev/null
    

install:
- ps: '$Env:ARTIFACT = "$($Env:APPVEYOR_BUILD_FOLDER)$([IO.Path]::DirectorySeparatorChar)Artifact"; mkdir $Env:ARTIFACT | out-null; Say "ARTIFACT folder: $($Env:ARTIFACT)"'
- ps: '$Env:SQL_SETUP_LOG_FOLDER = $Env:ARTIFACT; Say "SQL_SETUP_LOG_FOLDER is [$($Env:SQL_SETUP_LOG_FOLDER)]"'
- ps: Start-Transcript "Artifact\Detailed-Build.log" -Force
- git submodule update --init --recursive
- ps: |

    Say "Install Complete"

# - sh: 'mono --version || true; dotnet --info || true; '


before_build:
- ps: | 
    
    # Upgrade-PSReadLine

build_script:
- ps: | 
      Say "RESTORE and BUILD"
      & dotnet restore

- sh: |
      Say "Remove net 4.8 target for msbuild on linux"
      sed -i 's/net48;//g' Universe.CpuUsage/Universe.CpuUsage.csproj
      # cat Universe.CpuUsage/Universe.CpuUsage.csproj
      
- ps: |
      pushd Universe.CpuUsage
      #Say "Test using netcoreapp3.0"
      #& dotnet test -f netcoreapp3.0 -v n --test-adapter-path:. --logger:Appveyor
      Say "Rebuild and pack Release"
      & msbuild /t:"rebuild;pack" /p:Configuration=Release /v:q
      Say "Rebuild and pack Debug"
      & msbuild /t:"rebuild;pack" /p:Configuration=Debug /v:q
      popd

after_build:

test_script:
- ps: |
    Say ".NET Core Tests"
    pushd Universe.CpuUsage.Tests 
    & dotnet test -f netcoreapp3.0 --test-adapter-path:. --logger:Appveyor
    popd

- ps: |
    if ($isWindows) {
        Say ".NET Framework Tests"
        dotnet build -f net46 -c Debug
        pushd "Universe.CpuUsage.Tests\bin\Debug\net46"
        nunit3-console Universe.CpuUsage.Tests.dll --workers=1 "--result=Universe.CpuUsage.Tests.Result.xml;format=AppVeyor"
        popd
    }

- sh: |
      Say "Mono Tests: Copy the build folder"
      mkdir -p Tests4Linux/bin
      cp -r "Universe.CpuUsage/bin/Any CPU/Debug/." Tests4Linux/bin/

      Say "Mono Tests: nuget restore"
      pushd Tests4Linux
      nuget restore -verbosity quiet
      
      Say "Mono Tests: msbuild rebuild"
      cfg=Release
      msbuild /t:Rebuild /p:Configuration=$cfg /v:q
      
      pushd packages/NUnit.ConsoleRunner*/tools
      runner=$(pwd)/nunit3-console.exe
      popd
      Say "Mono Tests: Run Tests using '$runner'"

      pushd Universe.CpuUsage.MonoTests/bin/$cfg
      eval "$runner --workers=1 Universe.CpuUsage.MonoTests.exe --result=MonoTests.xml;format=AppVeyor" || (Say "TESTING NET 2.0 ERROR"; exit 666)
      popd
      
      popd
      Say "Mono Tests: Done"

- ps: | 

    Say "Pack working folder as the 'AppVeyor Build Folder.7z' artifact"
    & "7z" a -t7z -mx=3 -ms=on "AppVeyor Build Folder.7z" .
    Say "Bye-bye"

after_test:
- ps: Stop-Transcript;
# - cmd: bash -c 'time echo "Hello from $(bash --version)"'

# Error uploading artifact the storage: The underlying connection was closed: An unexpected error occurred on a send.
artifacts:
 - path: Artifact
 - path: 'AppVeyor Build Folder.7z'
