jobs:

  - job: Windows
    variables:
      OS: Windows
      LLVM: 9
    timeoutInMinutes: 299
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'windows-latest'
    steps:
    - powershell: |
        dotnet test -c Debug -f netcoreapp2.2 --collect:"XPlat Code Coverage" -- RunConfiguration.DisableAppDomain=true | cat
      displayName: 'Tests'

trigger:
- master

