variables:
    buildConfiguration: "Debug"
    testProject: "Universe.CpuUsage.Tests/Universe.CpuUsage.Tests.csproj"
    solution: "Universe.CpuUsage.sln"

jobs:

  - job: Arm64
    variables:
      OS: Linux
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      name: 'arm64-pool'
    steps:
      - template: azure-steps-nix.yml

  - job: Ubuntu_16_04
    variables:
      OS: Linux
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-16.04'
    steps:
      - template: azure-steps-nix.yml

  - job: Ubuntu_18_04
    variables:
      OS: Linux
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'ubuntu-18.04'
    steps:
      - template: azure-steps-nix.yml

  - job: VS2017
    variables:
      OS: Windows
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-steps-nix.yml

  - job: VS_Latest
    variables:
      OS: Windows
    timeoutInMinutes: 99
    cancelTimeoutInMinutes: 1
    pool:
      vmImage: 'vs2017-win2016'
    steps:
      - template: azure-steps-nix.yml

trigger:
  - master


